
server:
  port: 8080

spring:
  datasource:
    name: ds
    url: jdbc:mysql://localhost:3306/springbootvue?useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.machao.persist.model

pagehelper:
  reasonable: true